name: menu_app
description: "A new flutter project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  mockito: ^5.4.4
  cloud_firestore: ^4.17.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.0.0
  lottie: ^1.2.1
  google_fonts: ^6.2.1
  mysql1: ^0.20.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/Menu.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/Menu.png"

flutter:
  uses-material-design: true

  assets:
    - assets/