name: menu_app
description: "A new flutter project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  user_repository:
    path: packages/user_repository
  mockito: ^5.4.4
  cloud_firestore: ^4.15.10
  loading_animation_widget: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/